# Generated by Django 5.1.6 on 2025-02-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IPR", "In progress"),
                            ("FAL", "Failed"),
                            ("SUCC", "Successful"),
                        ],
                        default="IPR",
                        max_length=5,
                    ),
                ),
                ("srt_content", models.TextField()),
            ],
        ),
    ]
