# Generated by Django 5.1.6 on 2025-02-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_task_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("IPR", "In progress"),
                    ("PROC", "Under processing"),
                    ("FAL", "Failed"),
                    ("SUCC", "Successful"),
                ],
                default="IPR",
                max_length=5,
            ),
        ),
    ]
